### ISSUE TITLE
Update PyPI

### ISSUE THREAD

**Issue by spyoungtech** [spyoungtech/grequests#131]
To get PyPI updated, we need @kennethreitz to give permissions on the [grequests PyPI project](https://pypi.org/project/grequests/) to my PyPI user (also [spyoungtech](https://pypi.org/user/spyoungtech/)) to publish packages.

**Comment by spyoungtech** [comment]
We will probably start a new major version (4.0) of `grequests` in the next release.

**Comment by kennethreitz** [comment]
you should be all set!

**Comment by spyoungtech** [comment]
[v0.4.0](https://pypi.org/manage/project/grequests/release/0.4.0/) now live on PyPI!
