### ISSUE TITLE
How to convert response for a json

### ISSUE THREAD

**Issue by Falcao74** [spyoungtech/grequests#156]
If i use simple requests, i can convert response to json

in my case, the json has a data and metadata
How to convert grequests response in json['data'] to save in database? 

`
def get_data(urls):
    auth = ENV.AUTH
    reqs = [grequests.get(link, headers=auth) for link in urls]
    resp = grequests.map(reqs)
    return resp
`
 example of my json return:
`
  {
    "data": [
      {
        "id": 1234567890,
        "name": "Joe Hussini",
        "active": true,
        "email": "mail@mail.com",
        "gender_name": "male",
  
        "preferences": {
          "calls": true,
          "sms": true,
          "correspondence": true,
          "eletronic_mail": true
        },
        "created_at": "2022-02-23T16:45:27.634-03:00552130650003",
        "updated_at": "2022-02-23T16:45:27.634-03:00552130650003",
        "address": {
          "zipcode": "88888888",
          "street": "Major Valentine",
          "number": 1234,
          "complement": "appartment 21",
          "neighbour": "B",
          "state": "Ny",
          "city": "New York"
        }
      }
    ],
    "metadata": {
      "pagination": {
        "total_count": 1,
        "total_pages": 122,
        "page_size": 1,
        "current_page": 1
      }
    }
  }
`

**Comment by spyoungtech** [comment]
Responses from `grequests` _are_ `requests.Response` objects. They work the same way as in `requests`.

Note that `grequests.map` returns a _list_ of responses.
