### ISSUE TITLE
limit number of requests per second.

### ISSUE THREAD

**Issue by Koushikphy** [spyoungtech/grequests#157]
I have to query a API that has a limit for number of request per second. As a results several requests get failed. Is there a option in the `grequest` so that it makes only n request per second instead of all of them?

**Comment by spyoungtech** [comment]
@Koushikphy there is no builtin option for this. However, `grequests` is just a thin wrapper around `requests`, so solutions that work for `requests` should be adaptable for `grequests`. 

For example, if you implement a subclass of `requests.Session` that obeys rate limiting, you could pass that to the `session` keyword parameter. There are likely many existing packages in the ecosystem that already provide something like this.

As a simple example:

```python
import grequests
import requests
from gevent.time import sleep

class RateLimitedSession(requests.Session):
    def should_wait_for_rate_limit(self, request) -> bool:
        print('implement your rate limiting logic here')
        return True
    def send(self, request, **kwargs):
        while True:
            if self.should_wait_for_rate_limit(request):
                print('waiting for rate limit for request', request.url)
                sleep(0.1)
            else:
                print('sending request for', request.url)
                return super().send(request, **kwargs)

session = RateLimitedSession()

req_list = [grequests.get('https://httpbin.org/status/200', session=session) for _ in range(20)]

for resp in grequests.imap(req_list, size=10):
    print('resp:', resp)
```
