### ISSUE TITLE
Add index in imap

### ISSUE THREAD

**Issue by latot** [spyoungtech/grequests#159]
Hi!, thx for this lib!, I was looking long time ago how to do this in a fast way.

The actual imap function does not keep the order of map, is not necessary bad, but I think would be great if it can return the index.
At least in my case, the data usually need more things than the request it self, and the index help to identify and relate information.

Thx!

**Comment by spyoungtech** [comment]
Yeah, I can see the usefulness of the ability to enumerate the responses with the original indices of the request.

Should be easy to implement...

**Comment by spyoungtech** [comment]
#160 proposed a new function for this purpose.

usage:
```python
>>> rs = [grequests.get(f'https://httpbin.org/status/{code}') for code in range(200, 206)]
>>> for index, response in grequests.imap_enumerated(rs, size=5):
...     print(index, response)
1 <Response [201]>
0 <Response [200]>
4 <Response [204]>
2 <Response [202]>
5 <Response [205]>
3 <Response [203]>
```

**Comment by latot** [comment]
:O Great!
