### ISSUE TITLE
Grequests warning and crash

### ISSUE THREAD

**Issue by BIGdeadLock** [spyoungtech/grequests#163]
I'm using map to send multiple get requests.  This is the code:

responses = grequests.map(
                   [grequests.get(url, timeout=self._timeout) for url in url_pool],
                   size=self._max_requests)

When I start my flask server (before the line execute)
I get the following warning when using grequests:
![image](https://user-images.githubusercontent.com/64005996/226373361-8bab14c3-257d-48cd-8427-4ecf6db73aef.png)

If I ignore the error and run the code it crashes:
![image](https://user-images.githubusercontent.com/64005996/226373813-86bbece7-8239-4acc-a0b3-33922e0195e7.png)

I've import grequests before the requests library.

Environment:
- Python 3.8
- Windows

**Comment by spyoungtech** [comment]
You need to make sure gevent is imported first. Also, you need to use a gevent-compatible debugger.

I'm guessing this is the same fundamental issue in [your other issue](https://github.com/spyoungtech/grequests/issues/164) so, I am going to close this one in favor of using #164 for further discussion.

**Comment by BIGdeadLock** [comment]
Is it supposed to be imported before grequests? Anyhow, it is imported first. It's the first module to be imported in the project and I still get the warning
