### ISSUE TITLE
feature: Get timing metrics

### ISSUE THREAD

**Issue by chitralverma** [spyoungtech/grequests#179]
Any way to get timings for the requests with this lib? ability to get metrics like below would be great

- http_req_blocked: Time spent on DNS resolution, waiting for a connection from the pool, etc.
- http_req_connecting: Time spent establishing the TCP connection.
- http_req_tls_handshaking: Time spent performing the SSL/TLS handshake.
- http_req_sending: Time taken to send the HTTP request to the server.
- http_req_receiving: Time taken to receive the first byte of the response from the server.
- http_req_waiting: Time spent waiting for the server to start sending the response.
- http_req_duration: Total time taken from the start to the end of the request.

**Comment by spyoungtech** [comment]
This library does not provide any metrics or timings. However, there are other tools like profilers or tracing/telemetry agents that may help you achieve what you're looking for. 

As it stands, this is outside of the scope of `grequests` so I'm going to close this issue.
